# Generated by Django 4.2 on 2024-07-26 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_project.hasher
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('address', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['address'],
            },
        ),
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('door_open_url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_virtual_log_supervised', models.BooleanField(default=False)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lanes', to='api.checkpoint')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('document_number', models.CharField(blank=True, default=uuid.uuid4, max_length=36, null=True)),
                ('celular', models.CharField(blank=True, max_length=13, null=True)),
                ('id_hash', models.CharField(default=django_project.hasher.generate_hash, max_length=140)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('max_entry_time', models.IntegerField(default=5)),
                ('has_passe_id', models.BooleanField(default=True)),
                ('has_qr_down', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QrReader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=50)),
                ('allow_passe_id', models.BooleanField(default=True)),
                ('allow_passe_invitation', models.BooleanField(default=True)),
                ('allow_passe_permanent', models.BooleanField(default=True)),
                ('lane', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lane_reader', to='api.lane')),
            ],
        ),
        migrations.CreateModel(
            name='PersonSite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site_approve', models.BooleanField(default=False)),
                ('using_passe_id', models.BooleanField(default=False)),
                ('can_send_external', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inner_customer', to='api.person')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inner_site', to='api.site')),
            ],
        ),
        migrations.CreateModel(
            name='LogbookRegister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('max_entry_time', models.DateTimeField(blank=True, null=True)),
                ('passe_active', models.BooleanField(default=True)),
                ('passe_code', models.CharField(default=django_project.hasher.generate_hash, max_length=140)),
                ('plate', models.CharField(blank=True, max_length=20, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('method', models.CharField(blank=True, choices=[('ID', 'Passe ID'), ('I', 'Invitación'), ('D', 'Invitación Descargada')], max_length=2, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('lane_used', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='api.site')),
                ('user_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to='api.person')),
                ('user_invitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to='api.person')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('O', 'owner'), ('C', 'couple'), ('CR', 'children'), ('R', 'relative'), ('F', 'friend'), ('T', 'tenant'), ('OT', 'other')], default='O', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('can_use_passe_id', models.BooleanField(default=True)),
                ('can_send_invitations', models.BooleanField(default=True)),
                ('can_send_external', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='api.household')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_houses', to='api.person')),
            ],
        ),
        migrations.AddField(
            model_name='household',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_houses', to='api.site'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.site'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
