# Generated by Django 4.2 on 2024-07-26 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='household',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='householdperson',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='lane',
            name='door_open_url',
        ),
        migrations.RemoveField(
            model_name='lane',
            name='is_virtual_log_supervised',
        ),
        migrations.RemoveField(
            model_name='logbookregister',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='personsite',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='qrreader',
            name='allow_passe_permanent',
        ),
        migrations.AddField(
            model_name='personsite',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='api.person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personsite',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='api.site'),
        ),
    ]
